# Generated by Django 4.2.7 on 2025-09-05 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EthereumAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('balance', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_contract', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=66, unique=True)),
                ('value', models.DecimalField(decimal_places=18, max_digits=30)),
                ('gas_price', models.BigIntegerField()),
                ('gas_used', models.BigIntegerField()),
                ('block_number', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='tracker.ethereumaddress')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='tracker.ethereumaddress')),
            ],
        ),
        migrations.AddField(
            model_name='ethereumaddress',
            name='watchlists',
            field=models.ManyToManyField(blank=True, through='tracker.AddressWatchList', to='tracker.watchlist'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('balance', 'Balance Change'), ('transaction', 'New Transaction'), ('large_transaction', 'Large Transaction')], max_length=20)),
                ('threshold', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracker.ethereumaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='addresswatchlist',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ethereumaddress'),
        ),
        migrations.AddField(
            model_name='addresswatchlist',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.watchlist'),
        ),
        migrations.AlterUniqueTogether(
            name='addresswatchlist',
            unique_together={('address', 'watchlist')},
        ),
    ]
